---
- hosts: all
  remote_user: pi
  sudo: no
  
  vars:
    nodejs_version: 0.10.28
    nodejs_install_dir: /home/pi/nodejs
    rebar_version: 2.5.1
    rebar_install_dir: /home/pi/rebar
    couchdb_version: developer-preview-2.0
    couchdb_install_dir: /home/pi/couchdb

  tasks:
    - include: tasks/install-erlang.yml
    - include: tasks/install-nodejs.yml
    - include: tasks/install-rebar.yml
    - include: tasks/install-couchdb.yml

